/**
 * Extract paginated content from a Playwright page as clean HTML.
 *
 * Reads the light DOM of each fragment-container's contentRoot (slot),
 * stripping away debug chrome and shadow DOM wrappers.
 */

/**
 * Extract the innerHTML of each fragment-container's content slot.
 *
 * @param {import('playwright').Page} page
 * @returns {Promise<string[]>} Array of HTML strings, one per page
 */
export async function extractPages(page) {
	return page.evaluate(() => {
		const containers = document.querySelectorAll("page-container");
		return [...containers].map((pc) => {
			const fc = pc.querySelector("fragment-container");
			return fc?.contentRoot?.innerHTML ?? pc.innerHTML;
		});
	});
}

/**
 * Build an HTML string from extracted page content.
 *
 * @param {string[]} pages - innerHTML per page from extractPages()
 * @returns {string}
 */
export function buildHtml(pages) {
	return pages.map((html) => `<page-container>\n${html}\n</page-container>`).join("\n") + "\n";
}

/**
 * Extract the inspect report text generated by report.js.
 *
 * @param {import('playwright').Page} page
 * @returns {Promise<string|null>}
 */
export async function extractInspect(page) {
	return page.getAttribute("html", "data-inspect-report");
}
