/**
 * Line box measurement — CSS Inline Level 3 §4.3.
 *
 * Line boxes are fragmentation containers generated by an inline
 * formatting context. Their height is determined by the aligned
 * layout bounds of inline-level boxes, driven by font metrics
 * (ascent + descent + line_gap) for line-height: normal.
 *
 * All measurement uses Range.getClientRects() on live DOM elements
 * in the measurement area — no canvas probes or synthetic elements.
 *
 * At DPR 1, browsers floor line-height: normal to integer CSS pixels.
 * The targetDevicePixelRatio setting controls whether the engine matches this
 * behavior (floor) or returns raw sub-pixel values (DPR 2+).
 *
 * @module
 */

import { computedStyleMap } from "../styles/computed-style-map.js";
import { INLINE_TEXT } from "./collect-inlines.js";

// Target device pixel ratio

let targetDevicePixelRatio = typeof devicePixelRatio !== "undefined" ? devicePixelRatio : 1;

/**
 * Set the target device pixel ratio for line-height rounding.
 * At devicePixelRatio 1, line-height: normal values are floored
 * to integers to match browser behavior. At 2+, raw sub-pixel
 * values are returned.
 *
 * Called once during setup — the value persists for the layout flow.
 *
 * @param {number} value
 */
export function setTargetDevicePixelRatio(value) {
	targetDevicePixelRatio = value;
}

/** @returns {number} current target device pixel ratio */
export function getTargetDevicePixelRatio() {
	return targetDevicePixelRatio;
}

// Line measurement

/**
 * Whether a rect belongs to the same line as a cluster anchored on the
 * line's first rect. Rects on one visual line (main text plus `<sub>`,
 * `<sup>`, `<small>` or smaller font-size runs) overlap vertically; a rect
 * on the next line does not. Majority overlap (more than half the shorter
 * box) tolerates baseline shifts without merging adjacent lines.
 */
function sharesLine(rect, line) {
	const overlap = Math.min(rect.bottom, line.anchorBottom) - Math.max(rect.top, line.anchorTop);
	const minHeight = Math.min(rect.bottom - rect.top, line.anchorBottom - line.anchorTop);
	return minHeight > 0 && overlap > minHeight / 2;
}

function overlapsInline(rect, line) {
	return Math.min(rect.right, line.inlineEnd) > Math.max(rect.left, line.inlineStart);
}

function emptyLines() {
	return { count: 0, lineHeight: 0, firstLineHeight: 0, tops: [], inkTops: [], inkHeights: [] };
}

/**
 * Reduce a DOMRectList to per-line tops. getClientRects() can return several
 * rects for one visual line when it mixes inline metrics, so rects are
 * clustered into lines by vertical overlap rather than treating every
 * distinct top as a new line.
 *
 * `tops` lets callers read exact line positions rather than extrapolating
 * from a single lineHeight — extrapolation accumulates sub-pixel drift
 * across many lines. Line-height is taken from the gap between the last
 * two tops to avoid first-line distortion from ::before pseudo-elements
 * or mixed metrics.
 */
function reduceRectsToLines(rects) {
	if (rects.length === 0) return emptyLines();

	const lines = [];
	for (let i = 0; i < rects.length; i++) {
		const rect = rects[i];
		if (rect.width === 0 && rect.height === 0) continue;
		// A Range that fully contains inline elements may return the element's
		// fragment rects first and its descendant text rects afterwards. Match
		// every existing visual line rather than assuming DOMRect order is also
		// line order, or nested inline runs are counted twice.
		const last = lines.length > 0 ? lines[lines.length - 1] : null;
		const line =
			last && sharesLine(rect, last)
				? last
				: lines.find(
						(candidate) => sharesLine(rect, candidate) && overlapsInline(rect, candidate),
					);
		if (line) {
			line.top = Math.min(line.top, rect.top);
			line.bottom = Math.max(line.bottom, rect.bottom);
			line.inlineStart = Math.min(line.inlineStart, rect.left);
			line.inlineEnd = Math.max(line.inlineEnd, rect.right);
		} else {
			lines.push({
				anchorTop: rect.top,
				anchorBottom: rect.bottom,
				top: rect.top,
				bottom: rect.bottom,
				inlineStart: rect.left,
				inlineEnd: rect.right,
			});
		}
	}

	if (lines.length === 0) return emptyLines();

	lines.sort((a, b) => a.anchorTop - b.anchorTop);
	const tops = lines.map((line) => line.anchorTop);
	const lineHeight = tops.length >= 2 ? tops[tops.length - 1] - tops[tops.length - 2] : 0;
	const firstLineHeight = lines[0].anchorBottom - lines[0].anchorTop;
	return {
		count: lines.length,
		lineHeight,
		firstLineHeight,
		tops,
		// Ink geometry per line, anchored on the topmost rect of the line
		// rather than the first one in DOMRect order: a line that mixes an
		// atomic inline with text reports the atomic's edge, which is the
		// edge closest to the line box.
		inkTops: lines.map((line) => line.top),
		inkHeights: lines.map((line) => line.bottom - line.top),
	};
}

/**
 * Measure rendered line boxes inside an element.
 *
 * @param {Element} element
 * @returns {{ count: number, lineHeight: number, firstLineHeight: number, tops: number[] }}
 */
export function measureLines(element) {
	const range = document.createRange();
	range.selectNodeContents(element);
	return reduceRectsToLines(range.getClientRects());
}

/**
 * Measure rendered line boxes spanning a contiguous run of DOM nodes — used
 * by anonymous block boxes, which wrap inline content without a backing
 * element (CSS 2.1 §9.2.1.1).
 *
 * @param {Node[]} nodes - the anonymous block's inline child nodes
 * @returns {{ count: number, lineHeight: number, firstLineHeight: number, tops: number[] }}
 */
export function measureLinesAcrossNodes(nodes) {
	if (!nodes || nodes.length === 0) return emptyLines();
	const range = document.createRange();
	range.setStartBefore(nodes[0]);
	range.setEndAfter(nodes[nodes.length - 1]);
	return reduceRectsToLines(range.getClientRects());
}

// Line box extents

// Sub-pixel slack. Layout snaps line positions to 1/64 px, and a computed
// line-height such as `0.9 * 48px` does not reproduce the used advance
// exactly, so a difference below this is noise rather than a short line box.
const EXTENT_TOLERANCE = 0.0625;

/**
 * Redistribute block extent from over-tall lines onto lines that came out
 * shorter than the strut.
 *
 * A line box is never shorter than the block's strut (CSS Inline §4.3), so an
 * advance below it means the ink anchor of that line sits at a different
 * offset inside its line box than the anchor of the line before it — the error
 * is a transfer between two adjacent advances, not a change in their sum.
 * Moving the deficit back off the surplus lines restores each line's own
 * extent and leaves the total untouched. With no surplus to draw on the strut
 * is the value in doubt, and the advances are left as measured.
 */
function liftShortLines(advances, strut) {
	if (!(strut > 0) || advances.length < 2) return advances;

	let deficit = 0;
	let surplus = 0;
	for (const advance of advances) {
		if (advance < strut - EXTENT_TOLERANCE) deficit += strut - advance;
		else if (advance > strut) surplus += advance - strut;
	}
	if (deficit <= 0 || surplus <= 0) return advances;

	const moved = Math.min(deficit, surplus);
	const grow = moved / deficit;
	const shrink = moved / surplus;
	for (let i = 0; i < advances.length; i++) {
		const advance = advances[i];
		if (advance < strut - EXTENT_TOLERANCE) advances[i] = advance + (strut - advance) * grow;
		else if (advance > strut) advances[i] = advance - (advance - strut) * shrink;
	}
	return advances;
}

/**
 * Block-direction advance of each line box, in line order.
 *
 * Line boxes tile the block's content box, so line `i` spans
 * `[Σ extents[<i], Σ extents[<=i])` and any run of lines is sized by summing
 * its own slice. Interior boundaries come from the gaps between the lines' ink
 * anchors — the browser's own line positions, so a line taller than
 * `line-height` is measured rather than assumed. The last line takes the
 * residual against the block's content box: with no following line there is no
 * gap to measure, and `line-height` is the wrong answer for a line holding an
 * inline-block, an image, a larger font run or a raised/lowered box.
 *
 * `totalExtent` is only the extent of the line boxes when nothing else sizes
 * that content box, so the residual it implies is checked against what a line
 * box can be — at least the strut, at most its own ink plus a strut of leading
 * — and dropped when it is not. That covers a specified block-size, a
 * stretched flex or grid item, a table cell, a block-level pseudo-element and
 * anything else that inflates the box, without enumerating them.
 *
 * @param {{ inkTops: number[], inkHeights: number[] }} measured - measureLines() result
 * @param {number} lineHeight - the block's computed line-height (the strut)
 * @param {number|null} [totalExtent] - content-box extent of the block holding
 *   these lines, when known; null extrapolates the last line instead.
 * @returns {number[]}
 */
export function computeLineExtents(measured, lineHeight, totalExtent = null) {
	const tops = measured?.inkTops ?? [];
	const count = tops.length;
	if (count === 0) return [];

	const strut = lineHeight > 0 ? lineHeight : 0;
	const advances = new Array(count);
	let spanned = 0;
	// A measured gap is a rendered line box height, so the smallest of them
	// bounds the strut from above when `line-height: normal` had to be
	// measured off a line that carries something taller than the font.
	let strutFloor = strut;
	for (let i = 0; i < count - 1; i++) {
		const advance = Math.max(0, tops[i + 1] - tops[i]);
		advances[i] = advance;
		spanned += advance;
		if (advance < strutFloor) strutFloor = advance;
	}

	const lastInk = measured.inkHeights?.[count - 1] ?? 0;
	const ceiling = Math.max(strutFloor, lastInk) + strut + EXTENT_TOLERANCE;
	if (totalExtent > 0 && totalExtent - spanned <= ceiling) {
		advances[count - 1] = totalExtent - spanned;
		liftShortLines(advances, strut);
		if (advances[count - 1] >= strutFloor - EXTENT_TOLERANCE) return advances;
	}

	// No trustworthy content box: the last line advances like the one before it.
	advances[count - 1] = count > 1 ? Math.max(strut, advances[count - 2]) : strut;
	return liftShortLines(advances, strut);
}

/**
 * Count the number of rendered line boxes in an element.
 *
 * @param {Element} element
 * @returns {number}
 */
export function countLines(element) {
	return measureLines(element).count;
}

/**
 * Get the computed line height of an element in pixels.
 *
 * For line-height: normal, measures the actual rendered line gap
 * from the element (already laid out in the measurement area).
 * At DPR 1, the result is floored to match browser behavior.
 *
 * @param {Element} element
 * @returns {number} line height in pixels
 */
export function getLineHeight(element) {
	const map = computedStyleMap(element);
	const lh = map.get("line-height");

	// "normal" returns a keyword (no .unit property).
	// Measure the actual rendered line gap from the element itself.
	if (!lh || !lh.unit) {
		const measured = measureLines(element);
		const raw =
			measured.lineHeight > 0
				? measured.lineHeight
				: measured.firstLineHeight || map.get("font-size")?.value || 16;
		return targetDevicePixelRatio === 1 ? Math.floor(raw) : raw;
	}

	// Unitless line-height (e.g. 1.3) — computedStyleMap returns unit "number".
	// Multiply by font-size to resolve to px.
	if (lh.unit === "number") {
		const fs = map.get("font-size");
		return lh.value * (fs && fs.unit ? fs.value : 16);
	}

	return lh.value;
}

/**
 * Pick the rect a glyph actually renders at. `getClientRects()` on a
 * single-char range at a soft-wrap boundary can emit a leading
 * zero-width rect on the previous line; the rect with the largest top
 * is the one the glyph is drawn at.
 */
function renderedRect(rects) {
	if (rects.length === 0) return null;
	let best = rects[0];
	for (let i = 1; i < rects.length; i++) {
		if (rects[i].top > best.top) best = rects[i];
	}
	return best;
}

function charTop(range, textNode, offset) {
	const safeEnd = Math.min(offset + 1, textNode.textContent.length);
	if (offset >= safeEnd) return Infinity;
	range.setStart(textNode, offset);
	range.setEnd(textNode, safeEnd);
	const rect = renderedRect(range.getClientRects());
	return rect ? rect.top : Infinity;
}

/**
 * Visual line index of the character at `offset` (index into `lineTops`).
 * Snapping a rect-top to a known line-top eliminates sub-pixel drift.
 *
 * Returns -1 if the range has no rects, or `lineTops.length` if the
 * offset is past the end of the text node.
 */
function lineIndexAtOffset(range, textNode, offset, lineTops) {
	const safeEnd = Math.min(offset + 1, textNode.textContent.length);
	if (offset >= safeEnd) return lineTops.length;
	range.setStart(textNode, offset);
	range.setEnd(textNode, safeEnd);
	const rect = renderedRect(range.getClientRects());
	if (!rect) return -1;
	for (let i = lineTops.length - 1; i >= 0; i--) {
		if (rect.top >= lineTops[i]) return i;
	}
	return 0;
}

// Exclusive upper bound: a local offset must be a valid character index
// within domNode, so `endOffset` (one-past-last) is deliberately excluded.
function offsetToItemAndLocal(textItems, flatOffset) {
	for (const item of textItems) {
		if (flatOffset >= item.startOffset && flatOffset < item.endOffset) {
			return { item, local: flatOffset - item.startOffset };
		}
	}
	return null;
}

export function createMeasurer() {
	const range = document.createRange();

	return {
		charTop: (textNode, offset) => charTop(range, textNode, offset),

		/**
		 * Flat textContent offset of the first character that renders on
		 * `targetLineIndex`. Binary-searches against `lineTops` via
		 * `lineIndexAtOffset`, so the comparison is integer-valued.
		 *
		 * `getClientRects()` works for offscreen elements, so this works
		 * for `content-measure`'s offscreen layout harness.
		 *
		 * @param {Object[]} items - InlineItemsData.items
		 * @param {number[]} lineTops - measureLines(element).tops
		 * @param {number} targetLineIndex - index into lineTops (>= 1)
		 * @returns {number|null}
		 */
		offsetAtLine(items, lineTops, targetLineIndex) {
			if (targetLineIndex <= 0 || targetLineIndex >= lineTops.length) return null;

			const textItems = items.filter((it) => it.type === INLINE_TEXT);
			if (textItems.length === 0) return null;

			let lo = textItems[0].startOffset;
			let hi = textItems[textItems.length - 1].endOffset;

			while (lo < hi) {
				const mid = (lo + hi) >>> 1;
				const loc = offsetToItemAndLocal(textItems, mid);
				if (!loc) {
					lo = mid + 1;
					continue;
				}
				const line = lineIndexAtOffset(range, loc.item.domNode, loc.local, lineTops);
				if (line >= targetLineIndex) hi = mid;
				else lo = mid + 1;
			}
			return lo;
		},
	};
}

let sharedMeasurer = null;

export function getSharedMeasurer() {
	if (!sharedMeasurer) sharedMeasurer = createMeasurer();
	return sharedMeasurer;
}
