/**
 * Line box measurement — CSS Inline Level 3 §4.3.
 *
 * Line boxes are fragmentation containers generated by an inline
 * formatting context. Their height is determined by the aligned
 * layout bounds of inline-level boxes, driven by font metrics
 * (ascent + descent + line_gap) for line-height: normal.
 *
 * All measurement uses Range.getClientRects() on live DOM elements
 * in the measurement area — no canvas probes or synthetic elements.
 *
 * At DPR 1, browsers floor line-height: normal to integer CSS pixels.
 * The targetDevicePixelRatio setting controls whether the engine matches this
 * behavior (floor) or returns raw sub-pixel values (DPR 2+).
 *
 * @module
 */

import { computedStyleMap } from "../styles/computed-style-map.js";
import { INLINE_TEXT } from "./collect-inlines.js";

// Target device pixel ratio

let targetDevicePixelRatio = typeof devicePixelRatio !== "undefined" ? devicePixelRatio : 1;

/**
 * Set the target device pixel ratio for line-height rounding.
 * At devicePixelRatio 1, line-height: normal values are floored
 * to integers to match browser behavior. At 2+, raw sub-pixel
 * values are returned.
 *
 * Called once during setup — the value persists for the layout flow.
 *
 * @param {number} value
 */
export function setTargetDevicePixelRatio(value) {
	targetDevicePixelRatio = value;
}

/** @returns {number} current target device pixel ratio */
export function getTargetDevicePixelRatio() {
	return targetDevicePixelRatio;
}

// Line measurement

/**
 * Measure rendered line boxes in an element using getClientRects().
 *
 * Returns the line count, the array of line-box tops (absolute Y),
 * an accurate line height measured from the gap between the last two
 * line tops, and the first line box height (for single-line fallback).
 * Measuring from the last two tops avoids first-line distortion from
 * ::before pseudo-elements or mixed metrics.
 *
 * The `tops` array lets callers read exact line positions rather than
 * extrapolating from a single lineHeight — extrapolation accumulates
 * sub-pixel drift across many lines.
 *
 * @param {Element} element
 * @returns {{ count: number, lineHeight: number, firstLineHeight: number, tops: number[] }}
 */
export function measureLines(element) {
	const range = document.createRange();
	range.selectNodeContents(element);
	const rects = range.getClientRects();
	if (rects.length === 0) return { count: 0, lineHeight: 0, firstLineHeight: 0, tops: [] };

	const tops = [rects[0].top];
	for (let i = 1; i < rects.length; i++) {
		if (rects[i].top > tops[tops.length - 1]) {
			tops.push(rects[i].top);
		}
	}

	let lineHeight = 0;
	if (tops.length >= 2) {
		lineHeight = tops[tops.length - 1] - tops[tops.length - 2];
	}

	return { count: tops.length, lineHeight, firstLineHeight: rects[0].height, tops };
}

/**
 * Count the number of rendered line boxes in an element.
 *
 * @param {Element} element
 * @returns {number}
 */
export function countLines(element) {
	return measureLines(element).count;
}

/**
 * Get the computed line height of an element in pixels.
 *
 * For line-height: normal, measures the actual rendered line gap
 * from the element (already laid out in the measurement area).
 * At DPR 1, the result is floored to match browser behavior.
 *
 * @param {Element} element
 * @returns {number} line height in pixels
 */
export function getLineHeight(element) {
	const map = computedStyleMap(element);
	const lh = map.get("line-height");

	// "normal" returns a keyword (no .unit property).
	// Measure the actual rendered line gap from the element itself.
	if (!lh || !lh.unit) {
		const measured = measureLines(element);
		const raw =
			measured.lineHeight > 0
				? measured.lineHeight
				: measured.firstLineHeight || map.get("font-size")?.value || 16;
		return targetDevicePixelRatio === 1 ? Math.floor(raw) : raw;
	}

	// Unitless line-height (e.g. 1.3) — computedStyleMap returns unit "number".
	// Multiply by font-size to resolve to px.
	if (lh.unit === "number") {
		const fs = map.get("font-size");
		return lh.value * (fs && fs.unit ? fs.value : 16);
	}

	return lh.value;
}

// Text measurers — charTop / offsetAtY

/**
 * Shared charTop implementation for both Range and Caret measurers.
 * Returns the vertical position of a character at the given offset.
 */
function charTop(range, textNode, offset) {
	const safeEnd = Math.min(offset + 1, textNode.textContent.length);
	if (offset >= safeEnd) return Infinity;
	range.setStart(textNode, offset);
	range.setEnd(textNode, safeEnd);
	const rects = range.getClientRects();
	return rects.length > 0 ? rects[0].top : Infinity;
}

/**
 * Returns the bottom edge of a character's line box at the given offset.
 * Used by break-offset search: a line fits only when its bottom edge
 * is within the available space, avoiding sub-pixel top-edge drift.
 */
function charBottom(range, textNode, offset) {
	const safeEnd = Math.min(offset + 1, textNode.textContent.length);
	if (offset >= safeEnd) return Infinity;
	range.setStart(textNode, offset);
	range.setEnd(textNode, safeEnd);
	const rects = range.getClientRects();
	return rects.length > 0 ? rects[0].bottom : Infinity;
}

/**
 * Create a text measurer backed by the DOM Range API.
 *
 * Uses getClientRects() on the live DOM text to read the browser's
 * actual line layout, avoiding re-implementation of line breaking.
 */
export function createRangeMeasurer() {
	const range = document.createRange();
	return {
		charTop: (textNode, offset) => charTop(range, textNode, offset),
		charBottom: (textNode, offset) => charBottom(range, textNode, offset),
	};
}

// Lazy-initialized process-wide measurer shared by layout nodes.
let sharedMeasurer = null;

/**
 * Get the shared text measurer for layout. Lazily constructs a caret-based
 * measurer when the browser supports `caretPositionFromPoint()`, otherwise
 * a Range-based one. All layout nodes use the same instance to amortize
 * the cost of the backing Range.
 */
export function getSharedMeasurer() {
	if (!sharedMeasurer) {
		sharedMeasurer =
			typeof document.caretPositionFromPoint === "function"
				? createCaretMeasurer()
				: createRangeMeasurer();
	}
	return sharedMeasurer;
}

/**
 * Create a text measurer that extends the Range measurer with
 * caretPositionFromPoint() for finding break offsets in a single call.
 */
export function createCaretMeasurer() {
	const range = document.createRange();

	return {
		charTop: (textNode, offset) => charTop(range, textNode, offset),
		charBottom: (textNode, offset) => charBottom(range, textNode, offset),

		/**
		 * Find the flat textContent offset at a Y cutoff by hitting the
		 * browser's caret positioning directly.
		 *
		 * @param {Element} element - the inline formatting context element
		 * @param {Object[]} items - InlineItemsData.items
		 * @param {number} yCutoff - Y position to probe
		 * @returns {number|null} flat textContent offset, or null on miss
		 */
		offsetAtY(element, items, yCutoff) {
			const rect = element.getBoundingClientRect();
			const x = rect.left + 1;
			const pos = document.caretPositionFromPoint(x, yCutoff);
			if (!pos) return null;

			const node = pos.offsetNode;
			const localOffset = pos.offset;

			for (const item of items) {
				if (item.type === INLINE_TEXT && item.domNode === node) {
					return item.startOffset + localOffset;
				}
			}

			const walker = element.ownerDocument.createTreeWalker(element, NodeFilter.SHOW_TEXT);
			walker.currentNode = node.nodeType === Node.TEXT_NODE ? node : element;
			let textNode = walker.nextNode();
			while (textNode) {
				for (const item of items) {
					if (item.type === INLINE_TEXT && item.domNode === textNode) {
						return item.startOffset;
					}
				}
				textNode = walker.nextNode();
			}

			return null;
		},
	};
}
