/**
 * Line box measurement — CSS Inline Level 3 §4.3.
 *
 * Line boxes are fragmentation containers generated by an inline
 * formatting context. Their height is determined by the aligned
 * layout bounds of inline-level boxes, driven by font metrics
 * (ascent + descent + line_gap) for line-height: normal.
 *
 * All measurement uses Range.getClientRects() on live DOM elements
 * in the measurement area — no canvas probes or synthetic elements.
 *
 * At DPR 1, browsers floor line-height: normal to integer CSS pixels.
 * The targetDevicePixelRatio setting controls whether the engine matches this
 * behavior (floor) or returns raw sub-pixel values (DPR 2+).
 *
 * @module
 */

import { computedStyleMap } from "../styles/computed-style-map.js";
import { INLINE_TEXT } from "./collect-inlines.js";

// Target device pixel ratio

let targetDevicePixelRatio = typeof devicePixelRatio !== "undefined" ? devicePixelRatio : 1;

/**
 * Set the target device pixel ratio for line-height rounding.
 * At devicePixelRatio 1, line-height: normal values are floored
 * to integers to match browser behavior. At 2+, raw sub-pixel
 * values are returned.
 *
 * Called once during setup — the value persists for the layout flow.
 *
 * @param {number} value
 */
export function setTargetDevicePixelRatio(value) {
	targetDevicePixelRatio = value;
}

/** @returns {number} current target device pixel ratio */
export function getTargetDevicePixelRatio() {
	return targetDevicePixelRatio;
}

// Line measurement

/**
 * Reduce a DOMRectList (one rect per rendered line-box) to line tops.
 * `tops` lets callers read exact line positions rather than extrapolating
 * from a single lineHeight — extrapolation accumulates sub-pixel drift
 * across many lines. Line-height is taken from the gap between the last
 * two tops to avoid first-line distortion from ::before pseudo-elements
 * or mixed metrics.
 */
function reduceRectsToLines(rects) {
	if (rects.length === 0) return { count: 0, lineHeight: 0, firstLineHeight: 0, tops: [] };

	const tops = [rects[0].top];
	for (let i = 1; i < rects.length; i++) {
		if (rects[i].top > tops[tops.length - 1]) tops.push(rects[i].top);
	}

	const lineHeight = tops.length >= 2 ? tops[tops.length - 1] - tops[tops.length - 2] : 0;
	return { count: tops.length, lineHeight, firstLineHeight: rects[0].height, tops };
}

/**
 * Measure rendered line boxes inside an element.
 *
 * @param {Element} element
 * @returns {{ count: number, lineHeight: number, firstLineHeight: number, tops: number[] }}
 */
export function measureLines(element) {
	const range = document.createRange();
	range.selectNodeContents(element);
	return reduceRectsToLines(range.getClientRects());
}

/**
 * Measure rendered line boxes spanning a contiguous run of DOM nodes — used
 * by anonymous block boxes, which wrap inline content without a backing
 * element (CSS 2.1 §9.2.1.1).
 *
 * @param {Node[]} nodes - the anonymous block's inline child nodes
 * @returns {{ count: number, lineHeight: number, firstLineHeight: number, tops: number[] }}
 */
export function measureLinesAcrossNodes(nodes) {
	if (!nodes || nodes.length === 0) {
		return { count: 0, lineHeight: 0, firstLineHeight: 0, tops: [] };
	}
	const range = document.createRange();
	range.setStartBefore(nodes[0]);
	range.setEndAfter(nodes[nodes.length - 1]);
	return reduceRectsToLines(range.getClientRects());
}

/**
 * Count the number of rendered line boxes in an element.
 *
 * @param {Element} element
 * @returns {number}
 */
export function countLines(element) {
	return measureLines(element).count;
}

/**
 * Get the computed line height of an element in pixels.
 *
 * For line-height: normal, measures the actual rendered line gap
 * from the element (already laid out in the measurement area).
 * At DPR 1, the result is floored to match browser behavior.
 *
 * @param {Element} element
 * @returns {number} line height in pixels
 */
export function getLineHeight(element) {
	const map = computedStyleMap(element);
	const lh = map.get("line-height");

	// "normal" returns a keyword (no .unit property).
	// Measure the actual rendered line gap from the element itself.
	if (!lh || !lh.unit) {
		const measured = measureLines(element);
		const raw =
			measured.lineHeight > 0
				? measured.lineHeight
				: measured.firstLineHeight || map.get("font-size")?.value || 16;
		return targetDevicePixelRatio === 1 ? Math.floor(raw) : raw;
	}

	// Unitless line-height (e.g. 1.3) — computedStyleMap returns unit "number".
	// Multiply by font-size to resolve to px.
	if (lh.unit === "number") {
		const fs = map.get("font-size");
		return lh.value * (fs && fs.unit ? fs.value : 16);
	}

	return lh.value;
}

/**
 * Pick the rect a glyph actually renders at. `getClientRects()` on a
 * single-char range at a soft-wrap boundary can emit a leading
 * zero-width rect on the previous line; the rect with the largest top
 * is the one the glyph is drawn at.
 */
function renderedRect(rects) {
	if (rects.length === 0) return null;
	let best = rects[0];
	for (let i = 1; i < rects.length; i++) {
		if (rects[i].top > best.top) best = rects[i];
	}
	return best;
}

function charTop(range, textNode, offset) {
	const safeEnd = Math.min(offset + 1, textNode.textContent.length);
	if (offset >= safeEnd) return Infinity;
	range.setStart(textNode, offset);
	range.setEnd(textNode, safeEnd);
	const rect = renderedRect(range.getClientRects());
	return rect ? rect.top : Infinity;
}

/**
 * Visual line index of the character at `offset` (index into `lineTops`).
 * Snapping a rect-top to a known line-top eliminates sub-pixel drift.
 *
 * Returns -1 if the range has no rects, or `lineTops.length` if the
 * offset is past the end of the text node.
 */
function lineIndexAtOffset(range, textNode, offset, lineTops) {
	const safeEnd = Math.min(offset + 1, textNode.textContent.length);
	if (offset >= safeEnd) return lineTops.length;
	range.setStart(textNode, offset);
	range.setEnd(textNode, safeEnd);
	const rect = renderedRect(range.getClientRects());
	if (!rect) return -1;
	for (let i = lineTops.length - 1; i >= 0; i--) {
		if (rect.top >= lineTops[i]) return i;
	}
	return 0;
}

// Exclusive upper bound: a local offset must be a valid character index
// within domNode, so `endOffset` (one-past-last) is deliberately excluded.
function offsetToItemAndLocal(textItems, flatOffset) {
	for (const item of textItems) {
		if (flatOffset >= item.startOffset && flatOffset < item.endOffset) {
			return { item, local: flatOffset - item.startOffset };
		}
	}
	return null;
}

export function createMeasurer() {
	const range = document.createRange();

	return {
		charTop: (textNode, offset) => charTop(range, textNode, offset),

		/**
		 * Flat textContent offset of the first character that renders on
		 * `targetLineIndex`. Binary-searches against `lineTops` via
		 * `lineIndexAtOffset`, so the comparison is integer-valued.
		 *
		 * `getClientRects()` works for offscreen elements, so this works
		 * for `content-measure`'s offscreen layout harness.
		 *
		 * @param {Object[]} items - InlineItemsData.items
		 * @param {number[]} lineTops - measureLines(element).tops
		 * @param {number} targetLineIndex - index into lineTops (>= 1)
		 * @returns {number|null}
		 */
		offsetAtLine(items, lineTops, targetLineIndex) {
			if (targetLineIndex <= 0 || targetLineIndex >= lineTops.length) return null;

			const textItems = items.filter((it) => it.type === INLINE_TEXT);
			if (textItems.length === 0) return null;

			let lo = textItems[0].startOffset;
			let hi = textItems[textItems.length - 1].endOffset;

			while (lo < hi) {
				const mid = (lo + hi) >>> 1;
				const loc = offsetToItemAndLocal(textItems, mid);
				if (!loc) {
					lo = mid + 1;
					continue;
				}
				const line = lineIndexAtOffset(range, loc.item.domNode, loc.local, lineTops);
				if (line >= targetLineIndex) hi = mid;
				else lo = mid + 1;
			}
			return lo;
		},
	};
}

let sharedMeasurer = null;

export function getSharedMeasurer() {
	if (!sharedMeasurer) sharedMeasurer = createMeasurer();
	return sharedMeasurer;
}
